# Nome do aplicativo
spring.application.name=ecommerce

# Caminho da conexão
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce?createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo

# Usuário
spring.datasource.username=guilherme

# Senha
spring.datasource.password=123@Mudar

# Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Ativa a criação das tabelas
spring.jpa.hibernate.ddl-auto=create

# Exibe as SQLs
spring.jpa.show-sql=true

# Formata as SQLs
spring.jpa.properties.hibernate.format_sql=true

# Especifica o dialeto
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect